services:
  bootrecov-test:
    image: archlinux:latest
    privileged: true
    network_mode: host
    volumes:
      - .:/workspace/bootrecov
    working_dir: /workspace/bootrecov
    command: bash test/bootvm/boot_test_vm.sh
